### ISSUE TITLE
Authme incompatibility! 

### ISSUE THREAD

**Issue by Deeptanil** [freethemice/ReallyFakePlayers#1]
While using authme, authme generates a issue as the bot that is being added does not have an ip!

Here's the error.
```
[08:12:19] [Server thread/INFO]: [TitanBoxRFP] Deep player has been added.
[08:12:19] [Craft Scheduler Thread - 2 - AuthMe/WARN]: [AuthMe] Plugin AuthMe v5.6.0-beta2-b2453 generated an exception while executing task 1684
java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getAddress()" because the return value of "org.bukkit.entity.Player.getAddress()" is null
	at fr.xephi.authme.util.PlayerUtils.getPlayerIp(PlayerUtils.java:21) ~[AuthMe-5.6.0-beta2.jar:?]
	at fr.xephi.authme.process.join.AsynchronousJoin.processJoin(AsynchronousJoin.java:89) ~[AuthMe-5.6.0-beta2.jar:?]
	at fr.xephi.authme.process.Management.lambda$performJoin$6(Management.java:77) ~[AuthMe-5.6.0-beta2.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-408]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-408]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[08:12:19] [Server thread/WARN]: [TitanBoxRFP] Task #1680 for TitanBoxRFP v1.11.1_171 generated an exception
java.lang.UnsupportedOperationException: SuperPerms no group permissions.
	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayerGroups(Permission_SuperPerms.java:91) ~[Vault.jar:?]
	at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:637) ~[Vault.jar:?]
	at com.firesoftitan.play.titanbox.rfp.managers.FakePlayerManager.removeOldGroups(FakePlayerManager.java:164) ~[TitanBoxRFP.jar:?]
	at com.firesoftitan.play.titanbox.rfp.managers.FakePlayerManager$2.run(FakePlayerManager.java:132) ~[TitanBoxRFP.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by freethemice** [comment]
[TitanBoxRFP.zip](https://github.com/freethemice/ReallyFakePlayers/files/8125885/TitanBoxRFP.zip)
Try this version and see if it works

**Comment by freethemice** [comment]
[TitanBoxRFP.zip](https://github.com/freethemice/ReallyFakePlayers/files/8125946/TitanBoxRFP.zip)
No clue if this will work, but try it and let me know

**Comment by Deeptanil** [comment]
Nope
```
23.02 16:26:54 [Server] INFO [TitanBoxRFP] Deep player has been added.
23.02 16:26:54 [Server] WARN [AuthMe] Plugin AuthMe v5.6.0-beta2-b2453 generated an exception while executing task 1618
23.02 16:26:54 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getAddress()" because the return value of "org.bukkit.entity.Player.getAddress()" is null
23.02 16:26:54 [Server] INFO at fr.xephi.authme.util.PlayerUtils.getPlayerIp(PlayerUtils.java:21) ~[AuthMe-5.6.0-beta2.jar:?]
23.02 16:26:54 [Server] INFO at fr.xephi.authme.process.join.AsynchronousJoin.processJoin(AsynchronousJoin.java:89) ~[AuthMe-5.6.0-beta2.jar:?]
23.02 16:26:54 [Server] INFO at fr.xephi.authme.process.Management.lambda$performJoin$6(Management.java:77) ~[AuthMe-5.6.0-beta2.jar:?]
23.02 16:26:54 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
23.02 16:26:54 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
23.02 16:26:54 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
23.02 16:26:54 [Server] WARN [TitanBoxRFP] Task #1614 for TitanBoxRFP v1.11.1_171 generated an exception
23.02 16:26:54 [Server] INFO java.lang.UnsupportedOperationException: SuperPerms no group permissions.
23.02 16:26:54 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayerGroups(Permission_SuperPerms.java:91) ~[Vault.jar:?]
23.02 16:26:54 [Server] INFO at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:637) ~[Vault.jar:?]
23.02 16:26:54 [Server] INFO at com.firesoftitan.play.titanbox.rfp.managers.FakePlayerManager.removeOldGroups(FakePlayerManager.java:164) ~[TitanBoxRFP.jar:?]
23.02 16:26:54 [Server] INFO at com.firesoftitan.play.titanbox.rfp.managers.FakePlayerManager$2.run(FakePlayerManager.java:132) ~[TitanBoxRFP.jar:?]
23.02 16:26:54 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
23.02 16:26:54 [Server] WARN [FastLogin] Task #1619 for FastLogin v1.11-SNAPSHOT-033fdd5 generated an exception
23.02 16:26:54 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getAddress()" because "address" is null
23.02 16:26:54 [Server] INFO at com.github.games647.fastlogin.bukkit.FastLoginBukkit.getSessionId(FastLoginBukkit.java:227) ~[FastLoginBukkit.jar:?]
23.02 16:26:54 [Server] INFO at com.github.games647.fastlogin.bukkit.FastLoginBukkit.getSession(FastLoginBukkit.java:222) ~[FastLoginBukkit.jar:?]
23.02 16:26:54 [Server] INFO at com.github.games647.fastlogin.bukkit.listener.ConnectionListener.delayForceLogin(ConnectionListener.java:83) ~[FastLoginBukkit.jar:?]
23.02 16:26:54 [Server] INFO at com.github.games647.fastlogin.bukkit.listener.ConnectionListener.lambda$onPlayerJoin$0(ConnectionListener.java:73) ~[FastLoginBukkit.jar:?]
23.02 16:26:54 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
23.02 16:26:54 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by freethemice** [comment]
So the code is so deep, I can't fix it. but I did do a hotpatch for the spigot.jar. I'm not sure if it will work. It may also mess you your server, but its totally up to you
todo it.
1. backup your spigot.jar
2. open spigot.jar with 7-zip, or something 
3. open the Hotfix.zip with the same program
4. drag and drop the org folder in to the spigot.jar
5. hit yes on any dialog that my pop and close all the zip programs
[Hotfix.zip](https://github.com/freethemice/ReallyFakePlayers/files/8126267/Hotfix.zip)
