### ISSUE TITLE
LuckPerms Compatibility

### ISSUE THREAD

**Issue by tristiisch** [freethemice/ReallyFakePlayers#3]
Hello, I've an error while using LuckPerm :
```
[07:38:25 WARN]: [TitanBoxRFP] Task #19 for TitanBoxRFP v1.11.1_171 generated an exception
me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.

LuckPerms cannot respond to the request because to do so:
- it needs to lookup user data for '3f5f82ae-ade5-497a-a295-13135a1158f7' (an offline player) from the database

Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:155) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userGetGroups(LuckPermsVaultPermission.java:259) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.getPlayerGroups(AbstractVaultPermission.java:413) ~[?:?]
        at com.firesoftitan.play.titanbox.rfp.managers.FakePlayerManager.removeOldGroups(FakePlayerManager.java:164) ~[TitanBoxRFP.jar:?]
        at com.firesoftitan.play.titanbox.rfp.managers.FakePlayerManager$2.run(FakePlayerManager.java:127) ~[TitanBoxRFP.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
        
Can you fix it please for performance ?

**Comment by tristiisch** [comment]
Fixed here : https://github.com/tristiisch/ReallyFakePlayers/commit/b0a9ce92e4e2137ec307f58d5c2145b03eac2239
Simply run asynchronous task instead of running it on the main thread.
